# frontend/Dockerfile.prod
# ================= 构建阶段 =================
FROM node:22-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# ================= 生产阶段 ================= 
FROM nginx:alpine AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY infra/docker/nginx/tacticore.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]