services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile.prod
      target: prod  # 默认生产环境
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
      - ./infra/docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword123
    ports:
      - "27017:27017"

volumes:
  mongo_data: