# backend/Dockerfile.dev
FROM node:22-alpine AS development
WORKDIR /app

# 安装开发依赖
RUN npm install -g nodemon
COPY package*.json ./
RUN npm ci
COPY . .

# 启动开发服务器
RUN npx prisma generate
CMD ["npm", "run", "start:dev:docker"]