# backend/Dockerfile.dev
FROM node:22-alpine AS development
WORKDIR /app

# 安装开发依赖
RUN npm install -g nodemon
COPY package*.json ./
RUN npm ci
COPY . .

# 启动开发服务器
RUN npx prisma generate

# 设置脚本权限
RUN chmod +x ./scripts/init-db.sh
# 使用初始化脚本
CMD ["sh", "-c", "./scripts/init-db.sh && npm run start:dev:docker"]